---
- hosts: proteios
  tasks:
  - stat: path=/srv/www/thegpm/files/Yeast_EtOH1.mgf.gz
    register: course_files
  - name: Download
    when: course_files.stat.exists == False
    get_url: url=http://webdav.swegrid.se/snic/bils/lu_proteomics/pub/server/coursefiles.tar dest=/home/{{ ansible_ssh_user }}/coursefiles.tar
  - name: Uncompress archive
    unarchive: src=/home/{{ ansible_ssh_user }}/coursefiles.tar dest=/srv/www/thegpm copy=no owner=www-data
    become: yes
    become_method: sudo
    when: course_files.stat.exists == False
  - file: path=/home/{{ ansible_ssh_user }}/coursefiles.tar state=absent
  - copy: src=RegisterCourseMzMLProteios.pl dest=/home/{{ ansible_ssh_user }}/RegisterCourseMzMLProteios.pl mode=u+x
  - command: /home/{{ ansible_ssh_user }}/RegisterCourseMzMLProteios.pl
