---
# This ansible script will configure a fresh Ubuntu 14.04 LTS server with Diana 1.0.0
# The ruser variable needs to be set to the remote user. The installation will be made in the home folder of that user.
 
- hosts: diana
  vars:
    ruser: ubuntu
    rhome: "/home/{{ ruser }}"
  remote_user: "{{ ruser }}"
  tasks:
  - name: upgrade
    become: yes
    become_method: sudo
    apt: upgrade=dist update_cache=yes
  - name: "Check hosts file"
    lineinfile: dest=/etc/hosts line="{{ ansible_default_ipv4.address }} {{ ansible_hostname }} localhost" state=present
    when: ansible_default_ipv4.address is defined
    become: yes
    become_method: sudo
  - name: Check if a reboot is required
    register: file
    stat: path=/var/run/reboot-required get_md5=no
  - name: Reboot the server
    command: /sbin/reboot
    become: yes
    become_method: sudo
    when: file.stat.exists == true
  - name: Wait for server to restart
    local_action:
      module: wait_for
        host={{ inventory_hostname }}
        port=22
        delay=1
        timeout=300

  - name: ensure jdk 7 is installed
    become: yes
    become_method: sudo
    apt: pkg=openjdk-7-jdk state=latest
  - name: install python-pip
    become: yes
    become_method: sudo
    apt: pkg=python-pip
  - name: install python-dev
    become: yes
    become_method: sudo
    apt: pkg=python-dev
  - name: install nympy
    become: yes
    become_method: sudo
    pip: name=numpy version=1.8.0
  - name: install libblas-dev
    become: yes
    become_method: sudo
    apt: pkg=libblas-dev
  - name: install liblapack-dev
    become: yes
    become_method: sudo
    apt: pkg=liblapack-dev
  - name: install gfortran
    become: yes
    become_method: sudo
    apt: pkg=gfortran
  - name: install scipy
    become: yes
    become_method: sudo
    pip: name=scipy version=0.9.0
  - name: install matplotlib
    become: yes
    become_method: sudo
    apt: pkg=python-matplotlib
  - name: install sklearn
    become: yes
    become_method: sudo
    pip: name=scikit-learn version=0.13.1
  - name: install pandas
    become: yes
    become_method: sudo
    pip: name=pandas version=0.12.0
  - stat: path="{{ rhome }}/diana-1.0.0"
    register: diana_files
  - name: install zip
    become: yes
    become_method: sudo
    apt: pkg=zip
  - name: Download Diana
    when: diana_files.stat.exists == False
    get_url: url=http://proteomics.immunoprot.lth.se/diana/files/diana-1.0.0.zip dest="{{ rhome }}"
  - name: Uncompress diana
    unarchive: src="{{ rhome }}/diana-1.0.0.zip" dest="{{ rhome }}" copy=no
    when: diana_files.stat.exists == False 
  - lineinfile: dest="{{ rhome }}/.bashrc" line="export PATH=$PATH:~/bin/diana/bin"
  - lineinfile: dest="{{ rhome }}/.bashrc" line="export PYTHONPATH=~/bin/pyprophet/lib/python2.7/site-packages"
  - lineinfile: dest="{{ rhome }}/.bashrc" line="export DIANA_DIR=~/bin/diana"
  - file: path="{{ rhome }}/bin/diana" state=directory
  - file: path="{{ rhome }}/bin/pyprophet/lib/python2.7/site-packages" state=directory
  - command: python setup.py install --prefix=~/bin/pyprophet
    environment:
      PYTHONPATH: "{{ rhome }}/bin/pyprophet/lib/python2.7/site-packages"
    args:
      chdir: "{{ rhome }}/diana-1.0.0/pyprophet"
      creates: "{{ rhome }}/bin/pyprophet/bin/pyprophet"
  - stat: path="{{ rhome }}/bin/diana/bin"
    register: diana_binaries
  - command: mv "{{ rhome }}/diana-1.0.0/bin" "{{ rhome }}/bin/diana"
    when: diana_binaries.stat.exists == False
  - file:
     path: "{{ rhome }}/bin/diana/bin"
     mode: u+x
     recurse: yes
