---
- hosts: proteios
  tasks:
  - name: dinosaur file
    get_url: url=https://github.com/fickludd/dinosaur/releases/download/1.1.3/Dinosaur-1.1.3.free.jar dest=/home/proteios/Dinosaur-1.1.3.jar mode=u+x owner=tomcat7
    become: yes
    become_method: sudo
  - name: msInspect file
    get_url: url=http://webdav.swegrid.se/snic/bils/lu_proteomics/pub/server/msi dest=/home/proteios/viewerApp.jar mode=u+x owner=tomcat7
    become: yes
    become_method: sudo
  - name: Configure Proteios
    become: yes
    become_method: sudo
    replace: dest=/var/lib/tomcat7/webapps/proteios/WEB-INF/classes/msinspect.properties regexp="^msinspect\.local\.install\.path = .*" replace="msinspect.local.install.path = /home/proteios/"
  - replace: dest=/var/lib/tomcat7/webapps/proteios/WEB-INF/classes/msinspect.properties regexp="^msinspect\.local\.disabled = yes" replace="msinspect.local.disabled = no"
    become: yes
    become_method: sudo    
  - replace: dest=/var/lib/tomcat7/webapps/proteios/WEB-INF/classes/msinspect.properties regexp="^msinspect\.memory_in_megabytes = 512" replace="msinspect.memory_in_megabytes = 1024"
    become: yes
    become_method: sudo
  - replace: dest=/var/lib/tomcat7/webapps/proteios/WEB-INF/classes/dinosaur.properties regexp="^dinosaur\.local\.disabled = yes" replace="dinosaur.local.disabled = no"
    become: yes
    become_method: sudo
  - replace: dest=/var/lib/tomcat7/webapps/proteios/WEB-INF/classes/dinosaur.properties regexp="^dinosaur\.local\.install\.path = /local/Dinosaur" replace="dinosaur.local.install.path = /home/proteios"
    become: yes
    become_method: sudo
  - replace: dest=/var/lib/tomcat7/webapps/proteios/WEB-INF/classes/dinosaur.properties regexp="^dinosaur\.local\.program\.name = viewerApp.jar" replace="dinosaur.local.program.name = Dinosaur-1.1.3.jar"
    become: yes
    become_method: sudo
  - replace: dest=/var/lib/tomcat7/webapps/proteios/WEB-INF/classes/dinosaur.properties regexp="^dinosaur\.memory_in_megabytes = 512" replace="dinosaur.memory_in_megabytes = 3200"
    become: yes
    become_method: sudo

  - name: Restart tomcat
    become: yes
    become_method: sudo
    service: name=tomcat7 state=restarted
    

