---
- hosts: proteios
  tasks:
  - stat: path=/home/{{ ansible_ssh_user }}/srm-client-3.0.3
    register: srmclient
  - name: Unarchive SRM client
    when: srmclient.stat.exists == False
    unarchive: src=https://www.dcache.org/downloads/1.9/repo/3.0/srm-client-3.0.3.tar.gz dest=/home/{{ ansible_ssh_user }} remote_src=Yes
  - name: Create proxy script
    become: yes
    become_method: sudo
    lineinfile: dest=/usr/share/tomcat7/create_proxy.sh create=yes owner=tomcat7 mode=u+x line="#!/bin/bash"
  - name: Complete proxy script
    become: yes
    become_method: sudo
    lineinfile: dest=/usr/share/tomcat7/create_proxy.sh line='arcproxy --passwordsource="key=file:/usr/share/tomcat7/.gridpw"'
  - name: Configure Proteios
    become: yes
    become_method: sudo
    replace: dest=/var/lib/tomcat7/webapps/proteios/WEB-INF/classes/connection.properties regexp="^srm\.set\.permissions = .*" replace="srm.set.permissions = /home/{{ ansible_ssh_user }}/srm-client-3.0.3/bin/srm-get-permissions"   